#!/bin/bash
BLACK='\e[0;30m'
BLUE='\e[0;34m'
GREEN='\e[0;32m'
CYAN='\e[0;36m'
RED='\e[0;31m'
PURPLE='\e[0;35m'
BROWN='\e[0;33m'
LIGHTGRAY='\e[0;37m'
DARKGRAY='\e[1;30m'
LIGHTBLUE='\e[1;34m'
LIGHTGREEN='\e[1;32m'
LIGHTCYAN='\e[1;36m'
LIGHTRED='\e[1;31m'
LIGHTPURPLE='\e[1;35m'
YELLOW='\e[1;33m'
WHITE='\e[1;37m'
NC='\e[0m'              # No Color
clear
echo -e "${GREEN}"
echo "+===============================+"
echo "+-------------------------------+"
echo "+    ___  _               _     +"  
echo "+   | . || |_  ___  _ _ _| |_   +" 
echo "+   |   || . \/ . \| | | | |    +"  
echo "+   |_|_||___/\___/|___| |_|    +"
echo "+-------------------------------+"
echo "+===============================+"
echo -e "${LIGHTBLUE}[Project Name] ${BLUE}?    "
echo -e "${LIGHTBLUE}[Version] ${GREEN}    Stresser Version 1.0     "
echo -e "${LIGHTBLUE}[Release Date] ${RED} ?-?-21     "
echo -e "${LIGHTBLUE}[Size] ${RED}         ~201KB    "
echo -e " "
echo -e "${LIGHTBLUE}[Developed By] ${RED} Raining    "
echo -e "${LIGHTBLUE}[Coder] ${RED}        Raining   "
echo -e "${LIGHTBLUE}[Beta Tester] ${RED}  Raining   "
echo -e ""
echo -e "${LIGHTBLUE}[Disclaimer] "
echo -e "${RED}"
echo -e "No me hago responsable de el uso de este stresser."
echo -e "Este stresser esta hecho para trollear a tus AMIGOS con SU PERMISO, pero se puede usar sin el o a cualquier persona." 
echo -e "network equipment. It may be unlawful to use this software for purposes other"
echo -e "than its intended use"
echo -e ""
echo -e "NO LO ENVIES PUTO!"
read

